### ISSUE TITLE
Step as a comment still in progress

### ISSUE THREAD

**Issue by RachelSecurely** [savanna-projects/rhino-agent#120]
![image](https://user-images.githubusercontent.com/78795528/108681183-7db9ba00-74f7-11eb-922c-b056e3b7b945.png)

**Comment by gravity-api** [comment]
### Workaround
Use non-functional step such as (you can replace the comment with marked out action):
```
wait {1} /** click on {#login} using {id}
```

or an empty action (in future version)

```
do nothing /** this is a placeholder step for future use
```

### Why?
The steps in azure gets a special "runtime" id which identifies them - adding a blank step, will violate some logics and rules regarding to integrations and how Rhino builds a test case - so basically, Azure/Jira/TestRail connectors does not support blank steps scenario (which is an anti pattern of tests design).

You can still use comment out action with ```TextConnecter``` which is looser when creating a test case.
