### ISSUE TITLE
Register page (relevant to all) - bottom page doesn't invite the user to the next stage, need to add link to "Deployment" page (see inside the issue))

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-agent#17]
This is how our bottom page (for all pages) should look link:

Register
In order to execute your plugins using Gravity API, you need to create an account which identifies you. You need to provide an email and setting your password, which later will be used when you send Gravity requests.

Gravity user is email formatted. That means you do not need to provide a real email (no email verification), as long as the user name you choose is a standard email phrase.

Navigate to Gravity API Registration Page
Fill in the email you wish to register with
Set your password
Validate your password
Click on "Register" button
image_1_0.png

**Next step? you need to deploy Rhino (or Gravity we have an issue with phrases) API and Widget recorder
Deployment (link)**

**Comment by YanivAroch** [comment]
**FYI - we need to implement this as a "story" to the users and lead them - they will not be so independent at first**

**Comment by gravity-api** [comment]
Open different issue for each page suggesting which page it should lead to
