### ISSUE TITLE
when running some iterations the report reference to last iteration screenshots

### ISSUE THREAD

**Issue by RachelSecurely** [savanna-projects/rhino-agent#170]
![image](https://user-images.githubusercontent.com/78795528/131305391-21ab2416-5bd9-4114-8627-81572bfe01ce.png)

![image](https://user-images.githubusercontent.com/78795528/131305425-223ca0d5-364f-4b45-be93-ff0d10cb9e82.png)

**Comment by gravity-api** [comment]
resolved
