### ISSUE TITLE
IIS deployment - leads to 404 - page doesn't exists 

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-agent#19]

**Comment by YanivAroch** [comment]
and 

Your First Automation
Running on a Command Line

too

**Comment by gravity-api** [comment]
Open new issue for each document change

**Comment by YanivAroch** [comment]
**IISDeployment**
adding direct link to: https://github.com/savanna-projects/rhino-agent/blob/master/docs/pages/GettingStarted/IISDeployment.md

**YourFirstAutomation**
https://github.com/savanna-projects/rhino-agent/blob/master/docs/pages/GettingStarted/YourFirstAutomation.md
