### ISSUE TITLE
Json parser error when sending empty string value in session parameter of type json

### ISSUE THREAD

**Issue by devorabr** [savanna-projects/rhino-agent#211]
this regex not contais the end " on the "" case:
Regex.Replace(resolvedMacro, "(?<=[^\\\\\"])\"", "\\\"")

so there is an exception on the deseralized after that,
because the special characters break the json.

![Screenshot 2023-04-25 120559](https://user-images.githubusercontent.com/106070085/234230571-3b44fdd2-fb9c-450c-a1a1-10928bbafaa0.png)
![Json_regex](https://user-images.githubusercontent.com/106070085/234016808-7d988702-e491-4dae-8b8b-82bbaf7735d3.png)

**Comment by gravity-api** [comment]
Resolved.
All parameters can be saved as binary (base64)
