### ISSUE TITLE
Connector ALM section need to be part of main "Rhino API Reference Guide" and standalone  

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-agent#25]

**Comment by YanivAroch** [comment]
Rhino Recorder Widget settings
How to add configure Rhino widget

Rhino widget allows you to configure your A.L.M (Application lifecycle management) to load Rhino widget recorder test cases.
You can customize Rhino functionality by configuring:
•	Connector to your A.L.M 
•	Playback Options
•	Rhino Options
Configure A.L.M Connector 
1.	Mouseover Rhino widget icon.
2.	Click on Rhino widget settings icon. 
3.	Configure "Connector" settings:
3.1.	Connector Type: you need to select which connector type Rhino will connect according to supported A.L.M available in the drop-down list box. 
Rhino widget supports: Jira – Xray, Gurock – TestRail and Microsoft – Test management.
3.2.	Server Address: A.L.M server address which can be available as SaaS or as on premise. Sever address format must contains valid url and port over https protocol.
3.3.	Project (for Jira connector use the project key): To write/read test cases in your A.L.M you must provide valid which project Rhino will connect to. In the project section you need to add the precise name/id as it shows in your A.L.M project.
3.4.	Test suite or Test set id: You need to provide your test suite id or test case id under your project which you can create or update the recorded test case from Rhino.
3.4.1.	Microsoft DevOps (TFS) MTM:
3.4.2.	Jira cloud
3.4.3.	Jira TestRail example:
3.4.4.	Jira Xray example:
3.4.5.	Text File example:
3.5.	 User Name: A.L.M server user name credentials
3.6.	Password: A.L.M server password credentials

**Comment by gravity-api** [comment]
The connectors and Agent are different projects.
The connectors documentation can be found under the corresponding connector project.
