### ISSUE TITLE
Plugins - Get Plugin method doesn't allow to get all plugins 

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-agent#33]
page link
https://github.com/savanna-projects/rhino-agent/blob/master/docs/pages/ApiReference/Plugins.md#get-plugin

go to create a plugin 
Request Fields - The request body follows the same format as **Get Plugin** response content. 

the request body should be elaborated better for the user to understand what to send in the request and not as a link to "get plugin" **response**

**Comment by gravity-api** [comment]
it is elaborated here
https://github.com/savanna-projects/rhino-agent/blob/master/docs/pages/ApiReference/Plugins.md

Under Get Plugin documentation (as also suggested in the create plugin request fields)
