### ISSUE TITLE
Documentation - ServerSettings: "Next Step: Run Verification Tests" leads to typo on md file (see below)

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-agent#70]
https://github.com/savanna-projects/rhino-agent/blob/master/docs/pages/GettingStarted/ServerSettings.md

Next Step: Run Verification Tests leads to **"VerifyDeploymnet.md" instead of "VerifyDeployment.md"**

**Comment by gravity-api** [comment]
resolved
