### ISSUE TITLE
Documentation - VerifyDeployment: row 11. "you have registered with" link is broken (4o4)

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-agent#71]
https://github.com/savanna-projects/rhino-agent/blob/master/docs/pages/GettingStarted/VerifyDeployment.md

11. Set the user and password you have registered with under the user and password parameters
**leads to (no md ending):
https://github.com/savanna-projects/rhino-agent/blob/master/docs/pages/GettingStarted/Register**

**Comment by gravity-api** [comment]
resolved
