### ISSUE TITLE
Documentation - Regular Expression: "Locator" leads to actions and not locators 

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-agent#73]
https://github.com/savanna-projects/rhino-agent/blob/master/docs/pages/GettingStarted/WidgetOverviewActions.md
Regular Expression
locator 
leads to: 

https://github.com/savanna-projects/rhino-agent/blob/master/docs/pages/GettingStarted/WidgetOverviewActions.md#locators

**Comment by gravity-api** [comment]
resolved
