### ISSUE TITLE
Documentation - Connect to Widget: Requirements doesn't lean to Requirements section 

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-agent#79]
https://github.com/savanna-projects/rhino-agent/blob/master/docs/pages/GettingStarted/ConnectWidget.md

Requirements

https://github.com/savanna-projects/rhino-agent/blob/master/docs/pages/GettingStarted/ConnectWidget.md#requierments

**Comment by gravity-api** [comment]
resolved
